AppSIRI/Controllers/PujasController.cs
using AppSIRI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using System.Security.Claims;

namespace AppSIRI.Controllers
{
    public class PujasController : Controller
    {
        // GET: Pujas
        public ActionResult PujasRemate(string Id)
        {
            Guid auxId = Guid.Parse(Id);

            using (ApplicationDbContext objContext = new ApplicationDbContext())
            {
                var pujas = (from p in objContext.Pujas
                             where p.RemateIdFk == auxId
                             select p).ToList();
                ViewBag.puja = pujas;
            }

            return View();
        }

        // GET: Pujas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Pujas/Creat
        public ActionResult Create(string id)
        {
            Guid auxId = Guid.Parse(id);
            ViewBag.UserId = User.Identity.GetUserId();
            ViewBag.RemateId = auxId;
            return View();
        }

        // POST: Pujas/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "UserIdFk, RemateIdFk, valorPuja")]RematePorUsuarioModel pujas)
        {
            if (!ModelState.IsValid)
                return View(pujas);
            using (ApplicationDbContext objContext = new ApplicationDbContext())
            {
                try
                {
                    objContext.Pujas.Add(pujas);
                    objContext.SaveChanges();
                    return RedirectToAction("Remates", "Remates");
                }
                catch (Exception err)
                {
                    ModelState.AddModelError("", err.Message);
                    return View(pujas);
                }
            }
        }

        // GET: Pujas/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Pujas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pujas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Pujas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AppSIRI/Views/Pujas/Create.cshtml
@model AppSIRI.Models.RematePorUsuarioModel
@{
    ViewBag.Title = "Pujar remate";
    ViewBag.cardCategory = "Complete los campos";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-danger">
                    <h4 class="card-title">@ViewBag.Title</h4>
                    <p class="card-category">@ViewBag.cardCategory</p>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Create", "Pujas", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.valorPuja, new { @class = "bmd-label-floating" })
                                    @Html.TextBoxFor(m => m.valorPuja, new { @class = "form-control", Type = "number"})
                                    @Html.ValidationMessageFor(m => m.valorPuja, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <input type="hidden" value="@ViewBag.RemateId" name="RemateIdFk">
                        <input type="hidden" value="@ViewBag.UserId" name="UserIdFk">
                        <button type="submit" class="btn btn-danger pull-right">Pujar</button>
                        <div class="clearfix"></div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

AppSIRI/Views/Pujas/PujasRemate.cshtml
@{
    ViewBag.Title = "Pujas realizadas";
    ViewBag.SubTitle = "Listado";
}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-warning">
                        <h4 class="card-title ">@ViewBag.Title</h4>
                        <p class="card-category">@ViewBag.SubTitle</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class="text-info">
                                    <tr>
                                        <th>Valor de puja</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in ViewBag.puja)
                                    {
                                    <tr>
                                        <td>@item.valorPuja</td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>